
package br.com.drerp.financeiro.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.2
 * Sun Apr 22 19:24:31 BRT 2012
 * Generated source version: 2.5.2
 */

@XmlRootElement(name = "pagarConsultaParticular", namespace = "http://service.financeiro.drerp.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pagarConsultaParticular", namespace = "http://service.financeiro.drerp.com.br/", propOrder = {"arg0", "arg1"})

public class PagarConsultaParticular {

    @XmlElement(name = "arg0")
    private br.com.drerp.financeiro.model.transferencia.Pagador arg0;
    @XmlElement(name = "arg1")
    private br.com.drerp.financeiro.model.procedimento.Procedimento[] arg1;

    public br.com.drerp.financeiro.model.transferencia.Pagador getArg0() {
        return this.arg0;
    }

    public void setArg0(br.com.drerp.financeiro.model.transferencia.Pagador newArg0)  {
        this.arg0 = newArg0;
    }

    public br.com.drerp.financeiro.model.procedimento.Procedimento[] getArg1() {
        return this.arg1;
    }

    public void setArg1(br.com.drerp.financeiro.model.procedimento.Procedimento[] newArg1)  {
        this.arg1 = newArg1;
    }

}

