
package br.com.drerp.financeiro.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.2
 * Sun Apr 22 19:24:31 BRT 2012
 * Generated source version: 2.5.2
 */

@XmlRootElement(name = "listarEmpresasResponse", namespace = "http://service.financeiro.drerp.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listarEmpresasResponse", namespace = "http://service.financeiro.drerp.com.br/")

public class ListarEmpresasResponse {

    @XmlElement(name = "return")
    private br.com.drerp.financeiro.model.transferencia.Beneficiario[] _return;

    public br.com.drerp.financeiro.model.transferencia.Beneficiario[] getReturn() {
        return this._return;
    }

    public void setReturn(br.com.drerp.financeiro.model.transferencia.Beneficiario[] new_return)  {
        this._return = new_return;
    }

}

